import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ClientOnly from './components/ClientOnly'
import Projects from './components/Projects'
import Button from 'react-bootstrap/Button';
import {Col, Container, Row} from "react-bootstrap";

export default function Home() {
  return (
      <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

            <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
                integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                crossOrigin="anonymous"
            />

        </Head>
    <body>
    <Container>
        <ClientOnly>
            <Projects/>
        </ClientOnly>
    </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </body>
      </>
  )
}